### ISSUE TITLE
namespace name 'Guna'

### ISSUE THREAD

**Issue by ahmadali1998** [aliasar1/Hotel-Management-System#2]
I have this issue when i try to build the program

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Guna' could not be found (are you missing a using directive or an assembly reference?)	Hotel Management System	C:\Users\username\Desktop\Hotel-Management-System-master\Hotel Management System\Dashboard.Designer.cs	314	Active

may you please help me to solve it and thank you

**Comment by ahmadali1998** [comment]
![image](https://user-images.githubusercontent.com/62743169/236863534-66a776a0-143f-4053-81de-900fffa2e30a.png)

I solved the above problem by adding the dll file as a reference but i faced this problem 
may you tell me how to solve it and thank you

**Comment by aliasar1** [comment]
Try to run this command to directly configure it: 

dotnet add package Guna.UI2.WinForms --version 2.0.4.4
Update version to latest or according to compatibility of project.

**Comment by aneboy24** [comment]
I am still not able to solve this Guna Problem. i am using visual studio 2022 how can i get rid of it?

**Comment by SarimEffendi** [comment]
Assign me this issue.

**Comment by aliasar1** [comment]
@aneboy24  @ahmadali1998 Issue is fixed now!
